### ISSUE TITLE
I am having trouble with mouse clicks in Imgui triggers a click in my actual game

### ISSUE THREAD

**Issue by singed420** [Sh0ckFR/Universal-ImGui-D3D11-Hook#1]
I successfully complied your code into dll and injected in my D3D11 game.
But I am having trouble that my click in imgui menu triggers a click in my actual game as well, it is so annoying and it effect the game play experience.
Is there something I missed?
Any way to prevent the click input into my actualy game while I click the imgui menu?
Thanks in advance.

**Comment by Sh0ckFR** [comment]
Hello,

I think you need to hook your mouse events and return nothing if the mouse positions are on your ImGui menu, you can take a look in InputHook.cpp directly and read this for the theory :

https://www.unknowncheats.me/wiki/C%2B%2B:WindowsHookEx_Mouse

I could implement it in my source code later on my side to help you ;)

**Comment by singed420** [comment]
Thank you very much!, 
if you could implement it in your source that could help people a lot more to understand it.

**Comment by singed420** [comment]
have you added into your code yet? i just tried hook mouse event and return null while in imgui menu, but doesnt work. not sure what i did wrong

**Comment by Sh0ckFR** [comment]
Hello,

Not yet sorry, I'm too busy actually but I will take a look probably the next week :)

**Comment by singed420** [comment]
implemented?

**Comment by nefarius** [comment]
The last commit was 24 days ago so obviously **not**.

**Comment by CNLouisLiu** [comment]
You can see this link https://github.com/CNLouisLiu/Universal-ImGui-D3D11-Hook/blob/patch-1/InputHook.cpp

**Comment by Sh0ckFR** [comment]
@CNLouisLiu Your link is down, can you reupload it ? I will do a merge, thank you ;)

**Comment by ayebrtba** [comment]
LRESULT APIENTRY WndProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam)
{

if (ImGui::GetIO().MouseDrawCursor) { 

// switch (uMsg) stuff here

}

return CallWindowProc(oWndProc, hwnd, uMsg, wParam, lParam);
}
