### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by 0xR41N** [Sh0ckFR/Universal-ImGui-D3D11-Hook#12]
Hello, i'm new so it may be a dumb error, i tried everything i could though

https://imgur.com/a/0J21bsD

thanks

**Comment by Sh0ckFR** [comment]
Hello,

You need to add the minhook library (.lib) in your project

**Comment by Sh0ckFR** [comment]
Did you resolved your problem ?

**Comment by Struckus** [comment]
Hey so I was trying this and had the same issue as they did. I took your advice and built MinHook .lib added it as a file to my project and still get the issue any help? What is the build configuration? Any help would be much appreciated :)

**Comment by Sh0ckFR** [comment]
You need to build it in 64 bits in release mode (for minhook) and add the .lib in 64 bits to replace the old one (specify the .lib in your linked in the project options too)
