### ISSUE TITLE
libMinHook-x64-v140-mdd.lib

### ISSUE THREAD

**Issue by zveryga5** [Sh0ckFR/Universal-ImGui-D3D11-Hook#13]
when i compile gives me message "cannot open input file "libMinHook-x64-v140-mdd.lib"
I check this [issues8](https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook/issues/8) and this dont help.

**Comment by Sh0ckFR** [comment]
Recompile the minhook library, add the new lib file to your project and recompile your project, it will work
