### ISSUE TITLE
Drawing doesn't work

### ISSUE THREAD

**Issue by nvshent** [Sh0ckFR/Universal-ImGui-D3D11-Hook#14]
Hello, I'm a rookie. I have a question. After the DLL is injected, my game mouse will not work and the menu will not be displayed. Why?
I added debugging information to the menu source code, which is valid. But the menu is not visible

**Comment by Sh0ckFR** [comment]
Did you tried to attach a debugger ? if you game mouse is freeze, your game probably entered in an infinite loop or something like that, don't hesitate to place breakpoints too

**Comment by Sh0ckFR** [comment]
hello, did you resolved your issue ?

**Comment by ahmetabdi** [comment]
He is maybe using a newer version of imgui this repo is using old version

**Comment by Sh0ckFR** [comment]
Here's the new repo (this one will be deleted later) : https://github.com/Sh0ckFR/Universal-Dear-ImGui-Hook
