### ISSUE TITLE
ImGui interaction

### ISSUE THREAD

**Issue by alxbrn** [Sh0ckFR/Universal-ImGui-D3D11-Hook#2]
I saw in a previous Issue there was issues with mouse cursor, i was just wondering if this has been solved (I'm still having this issue).

**Comment by CNLouisLiu** [comment]
BOOL MoseInWindow() {
	if (MousePosx <= WindowPosx)
	{
		return false;
	}
	if (MousePosx > WindowPosx + WindowWidth)
	{
		return false;
	}
	if (MousePosy <= WindowPosy)
	{
		return false;
	}
	if (MousePosy > MousePosy + WindowHeight)
	{
		return false;
	}
	return true;
}
.....WndProc
case WM_LBUTTONDOWN: {
			GetIO().MouseDown[0] = true;
if (MoseInWindow())
{
return false
}
..................................................................
Good luck for you

**Comment by CNLouisLiu** [comment]
You can see this link https://github.com/CNLouisLiu/Universal-ImGui-D3D11-Hook/blob/patch-1/InputHook.cpp

**Comment by Sh0ckFR** [comment]
@CNLouisLiu Thank you I will test your fix later, can you open a pull request ?
