### ISSUE TITLE
Missing some files

### ISSUE THREAD

**Issue by TezzoeR** [Sh0ckFR/Universal-ImGui-D3D11-Hook#4]
![Desktop Screenshot 2019 06 11 - 21 10 20 84](https://user-images.githubusercontent.com/45249375/59299684-90da1700-8c8d-11e9-83d5-215a249102d8.png)

i tried to fix the include but if i change 1 i get 5 new errors

**Comment by Sh0ckFR** [comment]
Hello,

You need to import the ImGui and MinHook librairies in your project and compile with the correct sdk version if you tried to import and updated version.

Regards,
