### ISSUE TITLE
Not an Issue, but...

### ISSUE THREAD

**Issue by easly1989** [Sh0ckFR/Universal-ImGui-D3D11-Hook#5]
Hello!
I'm developing a plugin for ACT.
It works quite good while used outside of fullscreen applications (as it uses Windows Toasts to show messages).

What i would like to do is, show the same toast (or even something simple) in game, when it is in fullscreen mode.

I'll need to show this message only when i capture defined packet from the game (and all the code I have is C#, and I don't know if there is a way to comunicate with your hook to tell it to show and hide the window, and the message to show in that window).

**Do you think this is possible to accomplish using your universal hook?
Could you give me some hints or support on how to do that?**

my code is here: https://github.com/easly1989/ffxiv_act_dfassist

Sorry if the message is confusing, feel free to ask me any question
Hope you can help,
Thank you in advance,

Easly

**Comment by Sh0ckFR** [comment]
You can try to detect your packets with your C# application and control your C++ dll with a pipe, take a look here :

C++ part : https://github.com/erfg12/memory.dll/wiki/Make-a-Named-Pipe-DLL-(Cplusplus)
C# part : https://github.com/erfg12/memory.dll/wiki/Using-Named-Pipes
