### ISSUE TITLE
Failed to create a device and swapchain

### ISSUE THREAD

**Issue by MattR-bpr** [Sh0ckFR/Universal-ImGui-D3D11-Hook#6]
Well, I successfully built the dll, but when game executes it, I just get an message box "failed to create a device and swapchain". I don't know if I have to edit anything in the source files or whatever. Any help is appreciated. Ps. I only changed the window in dllmain.cpp file to match the one I'm hooking into.

**Comment by Sh0ckFR** [comment]
Did you compiled the dll for your game architecture ? you can try to log the HRESULT here to debug it or use your debugger with a breakpoint directly : [https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook/blob/e40efcdf227d7ba0c8d3c1745d212be711bff56f/d3d11hook.cpp#L143](https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook/blob/e40efcdf227d7ba0c8d3c1745d212be711bff56f/d3d11hook.cpp#L143)

**Comment by MattR-bpr** [comment]
Well, i'm a noob in terms of directx, but I'll try to debug it at the if statement. And by the "game architecture" you mean either 32bit or 64bit, right?

**Comment by Sh0ckFR** [comment]
Yes, 32 or 64bit, if you can attach a debugger to your game, you could debug it during the exception, this is the best way to know what is going on

**Comment by MattR-bpr** [comment]
Ok, I'll let you know if I get anything

**Comment by MattR-bpr** [comment]
Ok, I fixed it (hooray). The problem was that the device was created before the game got opened
![Burnout(TM) Paradise Remastered 12 08 2019 17_29_24](https://user-images.githubusercontent.com/54020396/62877222-df0ba500-bd26-11e9-9b76-4ef7c2fdec7f.png)

Thank you for the amazing library!

**Comment by Sh0ckFR** [comment]
You're welcome, I hope you have the legal right to use my library on this game, I'm not responsible :) have a good day.
