### ISSUE TITLE
Keyboard input does not work

### ISSUE THREAD

**Issue by MattR-bpr** [Sh0ckFR/Universal-ImGui-D3D11-Hook#7]
Hi, I want to input my text into the menu. This is my code:
``int Time = 0;
//some setup...
ImGui::InputInt("Time", &Time, 60);
//other things...``

I tested this in the example version from the imgui examples and it works fine. But I cannot get my input in your version. Perhaps I'm missing some flag. Also, I'm sorry if this was already solved, but I couldn't find any solution here so far. Let me know if it works for you or I need to add some additional flag. Thanks

**Comment by MattR-bpr** [comment]
oh, and if you wonder if the two buttons work, then yes, they increase/decrease the value

**Comment by MattR-bpr** [comment]
Well, if anyone's interested, it doesn't detect any input. I tried Ctrl+c Ctrl+a, Ctrl+v and nothing worked. `GetAsyncKeyState()` function works fine, bit I assume ImGui uses a different function...

**Comment by Randshot** [comment]
The reason for that is, that the Input/WndProc Hook doesn't call the ImGui WndProc function.
Alternatively, you can also manually populate the ImGui IO.

**Comment by Sh0ckFR** [comment]
https://github.com/Sh0ckFR/Universal-ImGui-D3D11-Hook/blob/master/InputHook.cpp If you take a look and like Randshot said, only mouse inputs are actually defined but you can add some keyboard inputs if you need

**Comment by MattR-bpr** [comment]
Yeah, I noticed that. So basically I just have to add a message for each key

**Comment by MattR-bpr** [comment]
Ok, thank you, it works ♥️. But before we close this, is it possible to make the input not applying to game? For example, when I input an integer and I press 6 on my number numberic keyboard, it actives a in-game built screen (which is annoying). Let me know if it is possible to make it working like that

**Comment by MattR-bpr** [comment]
Btw any chance you could add me on discord? I have no friend who has much experience with directx and having one would be helpful for me. PISros0724#5148 (not meant for others to spam my account 😛)

**Comment by Randshot** [comment]
@MattR-bpr Depends on the game. For some, you can just return `true` in the `WndProc` function.

**Comment by MattR-bpr** [comment]
Ok, I'll take a look. And this should replace the function in `InputHook.cpp`, right?

**Comment by Randshot** [comment]
Yes, pretty much. You can strip out this part though:
```cpp
    switch (msg)
    {
    case WM_SIZE:
        if (g_pd3dDevice != NULL && wParam != SIZE_MINIMIZED)
        {
            ImGui_ImplDX11_InvalidateDeviceObjects();
            CleanupRenderTarget();
            g_pSwapChain->ResizeBuffers(0, (UINT)LOWORD(lParam), (UINT)HIWORD(lParam), DXGI_FORMAT_UNKNOWN, 0);
            CreateRenderTarget();
            ImGui_ImplDX11_CreateDeviceObjects();
        }
        return 0;
    case WM_SYSCOMMAND:
        if ((wParam & 0xfff0) == SC_KEYMENU) // Disable ALT application menu
            return 0;
        break;
    case WM_DESTROY:
        PostQuitMessage(0);
        return 0;
    }
```

**Comment by MattR-bpr** [comment]
Yeah, so basically, I'd just replace the switch statements with
`if (ImGui_ImplWin32_WndProcHandler(hWnd, msg, wParam, lParam))
        return true;`

**Comment by MattR-bpr** [comment]
Well, I replaced the statements, it captures my input fine, but that still interacts with the game. I don't know if it's even possible to make it not interacting with the game... But those are only two keys, so it's not such big deal...

**Comment by Randshot** [comment]
Like I said. It works for some games, but not for others. Many games capture their input in a different way and would require you to hook (many) other functions.

**Comment by MattR-bpr** [comment]
My friend made ImGui menu for the same game, so I'll check if he's even succeeded. But like I said, it only affects two keys, so it isn't a big deal. If my friend's menu doesn't support that too, then it means it cannot be fixed

**Comment by MattR-bpr** [comment]
@Randshot well, low level keyboard proc may work, but I have no idea how to use it. Would you mind providing a simple example?

**Comment by Sh0ckFR** [comment]
https://www.unknowncheats.me/forum/c-and-c-/83707-setwindowshookex-example.html

This code could help you
