### ISSUE TITLE
cannot open input file "libMinHook-x64-v140-mdd.lib"

### ISSUE THREAD

**Issue by EchoHackCmd** [Sh0ckFR/Universal-ImGui-D3D11-Hook#8]
Every time I try to compile to the DLL it displays "cannot open input file "libMinHook-x64-v140-mdd.lib"".

**Comment by MattR-bpr** [comment]
You are probably compiling it for 32 bit version. The linker is set to x64, so you have to change it to x86 (which is 32 bit). I had this issue too and I fixed it like that iirc
