### ISSUE TITLE
Alpha blending issue with a Gamemaker stusio 2 game

### ISSUE THREAD

**Issue by artemking4-Projects** [Sh0ckFR/Universal-ImGui-D3D11-Hook#9]
Im trying to make a hack for a game called crashlands, and i need a menu for it. I choosen imgui and i now have a problem with blending. The menu is nearly invisible on any color, but fully visible on black. 

How can i fix that?

**Comment by Sh0ckFR** [comment]
hello, I'm sorry but I can't help you to make a cheat for legal reasons.
